name: enigma_web
description: Attempt to create unified API to control Enigma1 & Enigma2 web interfaces
version: 2.0.0
homepage: https://github.com/shaxxx/EnigmaWeb.Dart.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  logging: ^1.3.0
  dio: ^5.7.0
  xml: ^6.5.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.4.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
